version: "3.8"
services:
  homework3:
    image: domdiej/homework3
    build: .
    container_name: homework3
    ports:
      - "80:3000"
    environment:
      - PORT=80
    volumes:
      - ./:/app 
    command: ["node", "index.js"]